# Generated by Django 2.0.7 on 2018-07-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('abbreviation', models.TextField()),
                ('bhv_id', models.IntegerField(unique=True)),
            ],
        ),
    ]
