# Generated by Django 4.2.4 on 2023-10-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_globalmessage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="env",
            options={
                "verbose_name": "Umgebungsvariable",
                "verbose_name_plural": "Umgebungsvariablen",
            },
        ),
        migrations.AlterField(
            model_name="env",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
