# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.TextField()),
                ('player_number', models.TextField()),
                ('goals_total', models.PositiveIntegerField(default=0)),
                ('penalty_goals', models.PositiveIntegerField(default=0)),
                ('penalty_tries', models.PositiveIntegerField(default=0)),
                ('warning_time', models.DurationField(null=True)),
                ('first_suspension_time', models.DurationField(null=True)),
                ('second_suspension_time', models.DurationField(null=True)),
                ('third_suspension_time', models.DurationField(null=True)),
                ('disqualification_time', models.DurationField(null=True)),
                ('report_time', models.DurationField(null=True)),
                ('team_suspension_time', models.DurationField(null=True)),
            ],
        ),
    ]
