# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='association',
        ),
        migrations.AlterField(
            model_name='league',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='districts.District'),
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
