# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerscore',
            name='disqualification_time',
        ),
        migrations.RemoveField(
            model_name='playerscore',
            name='first_suspension_time',
        ),
        migrations.RemoveField(
            model_name='playerscore',
            name='penalty_tries',
        ),
        migrations.RemoveField(
            model_name='playerscore',
            name='player_number',
        ),
        migrations.RemoveField(
            model_name='playerscore',
            name='report_time',
        ),
        migrations.RemoveField(
            model_name='playerscore',
            name='second_suspension_time',
        ),
        migrations.RemoveField(
            model_name='playerscore',
            name='team_suspension_time',
        ),
        migrations.RemoveField(
            model_name='playerscore',
            name='third_suspension_time',
        ),
        migrations.RemoveField(
            model_name='playerscore',
            name='warning_time',
        ),
    ]
