# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorers', '0002_auto_20170925_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerscore',
            old_name='goals_total',
            new_name='goals',
        ),
    ]
