# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorers', '0004_auto_20171022_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.RemoveField(
            model_name='game',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='game',
            name='penalty_goals',
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set([('home_team', 'guest_team')]),
        ),
    ]
