# Generated by Django 4.1a1 on 2022-06-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leagues", "0002_update_league_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeagueName",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bhv_id", models.IntegerField(unique=True)),
                ("name", models.TextField()),
            ],
        ),
    ]
