# Generated by Django 6.0.5 on 2026-07-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leagues", "0003_leaguename"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="bhv_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="season",
            name="name",
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
