# Generated by Django 2.1.3 on 2018-11-20 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leagues", "0001_initial"),
        ("teams", "0001_initial"),
        ("sports_halls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.IntegerField()),
                ("opening_whistle", models.DateTimeField(blank=True, null=True)),
                ("home_goals", models.IntegerField(blank=True, null=True)),
                ("guest_goals", models.IntegerField(blank=True, null=True)),
                ("report_number", models.IntegerField(blank=True, null=True, unique=True)),
                (
                    "forfeiting_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forfeiting_team",
                        to="teams.Team",
                    ),
                ),
                (
                    "guest_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="guest_team", to="teams.Team"
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="home_team", to="teams.Team"
                    ),
                ),
                ("league", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="leagues.League")),
                (
                    "sports_hall",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="sports_halls.SportsHall"
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="game",
            unique_together={("number", "league")},
        ),
    ]
