# Generated by Django 5.0.3 on 2024-03-30 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_game_spectators"),
        ("sports_halls", "0001_initial"),
        ("teams", "0003_team_club"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="forfeiting_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forfeiting_team",
                to="teams.team",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="sports_hall",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="sports_halls.sportshall"
            ),
        ),
    ]
