# Generated by Django 4.2.4 on 2023-10-23 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "sports_halls",
            "0002_alter_sportshall_options_alter_sportshall_address_and_more",
        ),
        ("teams", "0003_alter_team_options_alter_team_bhv_id_and_more"),
        ("leagues", "0004_alter_league_options_alter_season_options_and_more"),
        ("games", "0002_game_spectators"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"verbose_name": "Spiel", "verbose_name_plural": "Spiele"},
        ),
        migrations.AlterField(
            model_name="game",
            name="guest_goals",
            field=models.IntegerField(blank=True, null=True, verbose_name="Gast"),
        ),
        migrations.AlterField(
            model_name="game",
            name="guest_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guest_team",
                to="teams.team",
                verbose_name="Gastmannschaft",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="home_goals",
            field=models.IntegerField(blank=True, null=True, verbose_name="Heim"),
        ),
        migrations.AlterField(
            model_name="game",
            name="home_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home_team",
                to="teams.team",
                verbose_name="Heimmannschaft",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="league",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="leagues.league",
                verbose_name="Liga",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="number",
            field=models.IntegerField(verbose_name="Spiel-Nr."),
        ),
        migrations.AlterField(
            model_name="game",
            name="opening_whistle",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Anpfiff"),
        ),
        migrations.AlterField(
            model_name="game",
            name="report_number",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="Bericht-Nr."
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="spectators",
            field=models.IntegerField(blank=True, null=True, verbose_name="Zuschauer"),
        ),
        migrations.AlterField(
            model_name="game",
            name="sports_hall",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sports_halls.sportshall",
                verbose_name="Sporthalle",
            ),
        ),
    ]
