# Generated by Django 4.2.4 on 2023-10-31 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0003_alter_team_options_alter_team_bhv_id_and_more"),
        ("leagues", "0004_alter_league_options_alter_season_options_and_more"),
        (
            "sports_halls",
            "0002_alter_sportshall_options_alter_sportshall_address_and_more",
        ),
        ("games", "0003_alter_game_options_alter_game_guest_goals_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="guest_goals",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="guest_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guest_team",
                to="teams.team",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="home_goals",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="home_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home_team",
                to="teams.team",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="league",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="leagues.league"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="number",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="game",
            name="opening_whistle",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="report_number",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="sports_hall",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sports_halls.sportshall",
            ),
        ),
    ]
