# Generated by Django 5.1.3 on 2024-12-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_alter_game_forfeiting_team_alter_game_sports_hall"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="remark",
            field=models.TextField(blank=True),
        ),
    ]
