# Generated by Django 5.2.6 on 2025-10-12 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_game_remark"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="forfeiting_team",
        ),
    ]
