# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('associations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('abbreviation', models.TextField(unique=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='associations.Association')),
            ],
        ),
    ]
