# Generated by Django 2.1.4 on 2018-12-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
