# Generated by Django 4.1a1 on 2022-06-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_alter_published_default_false"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportsBlacklist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_number", models.IntegerField(unique=True)),
                ("note", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
