# Generated by Django 5.1.3 on 2024-11-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0006_unify_players"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportsblacklist",
            name="note",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
