# Generated by Django 4.2.4 on 2023-10-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("associations", "0003_alter_association_options_and_more"),
        ("districts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="district",
            options={
                "ordering": ("bhv_id",),
                "verbose_name": "Bezirk",
                "verbose_name_plural": "Bezirke",
            },
        ),
        migrations.AlterField(
            model_name="district",
            name="associations",
            field=models.ManyToManyField(
                to="associations.association", verbose_name="Verbände"
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="bhv_id",
            field=models.IntegerField(unique=True, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="district",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Name"),
        ),
    ]
