# Generated by Django 2.1.1 on 2018-09-16 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leagues", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField()),
                ("short_name", models.TextField()),
                ("bhv_id", models.IntegerField(unique=True)),
                ("league", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="leagues.League")),
            ],
        ),
        migrations.AlterUniqueTogether(name="team", unique_together={("name", "league"), ("short_name", "league")}),
    ]
