# Generated by Django 2.2.4 on 2019-08-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='retirement',
            field=models.DateField(blank=True, null=True),
        ),
    ]
