# Generated by Django 4.1.2 on 2023-11-05 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("associations", "0001_initial"),
        ("teams", "0002_team_retirement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("bhv_id", models.IntegerField(unique=True)),
                ("associations", models.ManyToManyField(to="associations.association")),
            ],
        ),
        migrations.AddField(
            model_name="team",
            name="club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="teams.club",
            ),
        ),
    ]
