# Generated by Django 4.2.4 on 2023-10-23 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0004_alter_league_options_alter_season_options_and_more"),
        ("teams", "0002_team_retirement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={
                "verbose_name": "Mannschaft",
                "verbose_name_plural": "Mannschaften",
            },
        ),
        migrations.AlterField(
            model_name="team",
            name="bhv_id",
            field=models.IntegerField(unique=True, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="team",
            name="league",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="leagues.league",
                verbose_name="Liga",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="team",
            name="retirement",
            field=models.DateField(blank=True, null=True, verbose_name="Abgemeldet am"),
        ),
        migrations.AlterField(
            model_name="team",
            name="short_name",
            field=models.CharField(max_length=255, verbose_name="Abkürzung"),
        ),
    ]
