# Generated by Django 5.0.3 on 2024-03-26 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0001_initial"),
        ("teams", "0002_team_retirement"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clubs.club",
            ),
        ),
    ]
