# Generated by Django 4.2.4 on 2023-08-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("associations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="association",
            name="source_url",
            field=models.TextField(default="https://www.handball4all.de/home/portal"),
            preserve_default=False,
        ),
    ]
