# Generated by Django 4.2.4 on 2023-10-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("associations", "0002_association_source_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="association",
            options={"verbose_name": "Verband", "verbose_name_plural": "Verbände"},
        ),
        migrations.RemoveField(
            model_name="association",
            name="source_url",
        ),
        migrations.AlterField(
            model_name="association",
            name="abbreviation",
            field=models.CharField(max_length=255, verbose_name="Abkürzung"),
        ),
        migrations.AlterField(
            model_name="association",
            name="bhv_id",
            field=models.IntegerField(unique=True, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="association",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Name"),
        ),
    ]
