# Generated by Django 5.2.6 on 2025-10-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associations", "0002_association_source_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="association",
            name="abbreviation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
