# Generated by Django 5.2.6 on 2025-10-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associations", "0003_association_abbreviation_optional"),
    ]

    operations = [
        migrations.RenameField(
            model_name="association",
            old_name="bhv_id",
            new_name="short_name",
        ),
        migrations.AlterField(
            model_name="association",
            name="short_name",
            field=models.TextField(unique=True),
        ),
    ]
