# Generated by Django 2.1.1 on 2018-09-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SportsHall",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.IntegerField(unique=True)),
                ("name", models.TextField()),
                ("address", models.TextField()),
                ("phone_number", models.TextField(blank=True, null=True)),
                ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("bhv_id", models.IntegerField(unique=True)),
            ],
        ),
    ]
