# Generated by Django 4.2.4 on 2023-10-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sports_halls", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sportshall",
            options={
                "verbose_name": "Sporthalle",
                "verbose_name_plural": "Sporthallen",
            },
        ),
        migrations.AlterField(
            model_name="sportshall",
            name="address",
            field=models.CharField(max_length=255, verbose_name="Adresse"),
        ),
        migrations.AlterField(
            model_name="sportshall",
            name="bhv_id",
            field=models.IntegerField(unique=True, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="sportshall",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="sportshall",
            name="number",
            field=models.IntegerField(unique=True, verbose_name="Hallennummer"),
        ),
        migrations.AlterField(
            model_name="sportshall",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Telefonnummer"
            ),
        ),
    ]
