# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-21 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('abbreviation', models.TextField()),
                ('bhv_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('bhv_id', models.IntegerField(unique=True)),
                ('associations', models.ManyToManyField(to='base.Association')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('opening_whistle', models.DateTimeField()),
                ('home_goals', models.IntegerField(blank=True, null=True)),
                ('guest_goals', models.IntegerField(blank=True, null=True)),
                ('report_number', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('abbreviation', models.TextField()),
                ('bhv_id', models.IntegerField(unique=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.District')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_number', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('penalty_goals', models.IntegerField()),
                ('penalty_tries', models.IntegerField()),
                ('warning_time', models.DurationField(blank=True, null=True)),
                ('first_suspension_time', models.DurationField(blank=True, null=True)),
                ('second_suspension_time', models.DurationField(blank=True, null=True)),
                ('third_suspension_time', models.DurationField(blank=True, null=True)),
                ('disqualification_time', models.DurationField(blank=True, null=True)),
                ('report_time', models.DurationField(blank=True, null=True)),
                ('team_suspension_time', models.DurationField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Player')),
            ],
        ),
        migrations.CreateModel(
            name='SportsHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('bhv_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('short_name', models.TextField()),
                ('bhv_id', models.IntegerField(unique=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.League')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='forfeiting_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forfeiting_team', to='base.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='guest_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_team', to='base.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='base.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.League'),
        ),
        migrations.AddField(
            model_name='game',
            name='sports_hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.SportsHall'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set([('name', 'league'), ('short_name', 'league')]),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set([('player', 'game')]),
        ),
        migrations.AlterUniqueTogether(
            name='league',
            unique_together=set([('abbreviation', 'district'), ('name', 'district')]),
        ),
    ]
