# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='bhv_id',
            new_name='report_number',
        ),
    ]
