# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-21 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_env'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='opening_whistle',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
