# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-06 01:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20180305_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='opening_whistle',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 6, 1, 50, 20, 71654)),
            preserve_default=False,
        ),
    ]
