# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-08 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_game_opening_whistle'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='guest_goals',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='home_goals',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
