# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-21 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20180321_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='sports_hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.SportsHall'),
        ),
    ]
