# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-23 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20180321_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='player_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
