# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-11 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20180310_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='player_number',
            field=models.PositiveIntegerField(default=-1),
            preserve_default=False,
        ),
    ]
