# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-11 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_score_player_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='disqualification_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='first_suspension_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='penalty_tries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='second_suspension_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='team_suspension_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='third_suspension_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='warning_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
