# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-11 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20180311_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='goals',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='penalty_goals',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='penalty_tries',
            field=models.PositiveIntegerField(),
        ),
    ]
