# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-12 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20180311_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('phone_number', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='sports_hall',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.SportsHall'),
            preserve_default=False,
        ),
    ]
