# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-12 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20180312_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='report_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
