# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-12 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_score_report_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportshall',
            name='bhv_id',
            field=models.PositiveIntegerField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='guest_goals',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='sportshall',
            name='number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
