# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-13 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20180312_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='guest_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='goals',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='penalty_goals',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='penalty_tries',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='player_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sportshall',
            name='bhv_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='sportshall',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
