# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('districts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('abbreviation', models.TextField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='districts.District')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='league',
            unique_together=set([('name', 'district'), ('abbreviation', 'district')]),
        ),
    ]
