# Generated by Django 2.0.7 on 2018-07-10 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_number', models.IntegerField(blank=True, null=True)),
                ('goals', models.IntegerField()),
                ('penalty_goals', models.IntegerField()),
                ('penalty_tries', models.IntegerField()),
                ('warning_time', models.DurationField(blank=True, null=True)),
                ('first_suspension_time', models.DurationField(blank=True, null=True)),
                ('second_suspension_time', models.DurationField(blank=True, null=True)),
                ('third_suspension_time', models.DurationField(blank=True, null=True)),
                ('disqualification_time', models.DurationField(blank=True, null=True)),
                ('report_time', models.DurationField(blank=True, null=True)),
                ('team_suspension_time', models.DurationField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('player', 'game')},
        ),
    ]
