# Generated by Django 2.1.1 on 2018-09-24 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField()),
                ('name', models.TextField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_number', models.IntegerField(blank=True, null=True)),
                ('goals', models.IntegerField()),
                ('penalty_goals', models.IntegerField()),
                ('penalty_tries', models.IntegerField()),
                ('warning_time', models.DurationField(blank=True, null=True)),
                ('first_suspension_time', models.DurationField(blank=True, null=True)),
                ('second_suspension_time', models.DurationField(blank=True, null=True)),
                ('third_suspension_time', models.DurationField(blank=True, null=True)),
                ('disqualification_time', models.DurationField(blank=True, null=True)),
                ('report_time', models.DurationField(blank=True, null=True)),
                ('team_suspension_time', models.DurationField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('player', 'game')},
        ),
    ]
