name: CI Build

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: "3.7"
      - name: Install Pipenv
        run: python -m pip install --upgrade pipenv
      - name: Cache Pipenv
        id: cache-pipenv
        uses: actions/cache@v2.1.6
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}
      - name: Set up locale
        run: |
          sudo locale-gen de_DE.UTF-8
          sudo dpkg-reconfigure locales
      - name: Checkout Repository
        uses: actions/checkout@v2.3.5
      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: pipenv install --deploy --dev
      - name: Run tests with coverage
        run: pipenv run hbcoverage
      - name: Generate coverage report
        run: pipenv run coverage xml
      - name: Upload coverage report
        uses: actions/upload-artifact@v2.2.4
        with:
          name: coverage report
          path: coverage.xml

  codacy:
    runs-on: ubuntu-latest
    needs: main
    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v2.0.10
        with:
          name: coverage report
      - uses: codacy/codacy-coverage-reporter-action@v1.1.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml

  codeclimate:
    runs-on: ubuntu-latest
    needs: main
    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v2.0.10
        with:
          name: coverage report
      - uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

  codecov:
    runs-on: ubuntu-latest
    needs: main
    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v2.0.10
        with:
          name: coverage report
      - uses: codecov/codecov-action@v2.1.0

  coveralls:
    runs-on: ubuntu-latest
    needs: main
    steps:
      - uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  typing:
    runs-on: ubuntu-latest
    needs: main
    steps:
      - name: Run Mypy
        run: pipenv run mypy src

  styleguide:
    runs-on: ubuntu-latest
    needs: main
    steps:
      - name: Run Flake8
        run: pipenv run flake8

  attributions:
    runs-on: ubuntu-latest
    needs: main
    steps:
      - name: Compare attributions file with actual dependencies
        run: diff ATTRIBUTIONS.csv <(pipenv run attributions)

  licenses:
    runs-on: ubuntu-latest
    steps:
      - name: Download FOSSA CLI
        run: "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"
      - name: Checkout Repository
        uses: actions/checkout@v2.3.5
      - name: "Run FOSSA Scan"
        uses: fossas/fossa-action@v1.1.0
        with:
          api-key: ${{secrets.FOSSA_API_KEY}}
      - name: "Run FOSSA Test"
        uses: fossas/fossa-action@v1.1.0
        with:
          api-key: ${{secrets.FOSSA_API_KEY}}
          run-tests: true

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: djbrown/hbscorez:latest
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
